name: 'Create Docker Repository'
description: 'Creates a Docker repository on Docker Hub'
inputs:
  ecr_repository:
    description: 'The name of the Docker repository to create'
    required: true
  docker_username:
    description: 'Docker Hub username'
    required: true
  docker_password:
    description: 'Docker Hub password'
    required: true
outputs:
  docker_repository:
    description: 'The name of the Docker repository created'
    value: '${{ inputs.ecr_repository }}'
runs:
  using: 'composite'
  steps:
    - name: Obtain Docker Hub JWT Token
      id: get-jwt-token
      run: |
            token=$(curl -s -X POST https://hub.docker.com/v2/users/login/ \
                -H "Content-Type: application/json" \
                -d '{"username": "${{ inputs.docker_username }}", "password": "${{ inputs.docker_password }}"}' \
                | jq -r .token)
            echo "DOCKER_JWT_TOKEN=$token" >> $GITHUB_ENV

    - name: Create Docker Repository
      id: create-repo
      shell: bash
      run: |
        curl --location 'https://hub.docker.com/v2/repositories/${{ inputs.docker_username }}/' \
        --header 'Authorization: Bearer ${{ secrets.DOCKER_JWT_TOKEN }}' \
        --header 'Content-Type: application/json' \
        --data '{
            "name": "${{ inputs.ecr_repository }}",
            "is_private": true
        }' || echo "${{ inputs.ecr_repository }} Repository already exists."